### ISSUE TITLE
Error while npm install

### ISSUE THREAD

**Issue by siddhuoo7** [jwulf/zeebe-garage-benchmark#1]
![2020-11-05 17_58_53-45 19](https://user-images.githubusercontent.com/43318941/98241531-1819e000-1f91-11eb-8d16-a644bfbb2694.png)

**Comment by jwulf** [comment]
Did you check the segfault-handler repo for this error?

**Comment by jwulf** [comment]
I updated the zeebe-node dependency. This should fix this for you, as the segfault handler package has been removed.
